name: Cache common Docker images

runs:
  using: composite
  steps:
    - name: Set up GHA cache
      id: cache
      uses: actions/cache@v4
      with:
        path: cached_images.tar
        key: ${{ runner.os }}-cache

    - name: Cache images
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        docker pull dockereng/export-build
        docker pull golang
        docker save dockereng/export-build golang -o cached_images.tar

    - name: Restore cached images
      if: steps.cache.outputs.cache-hit == 'true'
      shell: bash
      run: docker load -i cached_images.tar
