channels:
  - conda-forge

dependencies:
  - astunparse
  - cffi
  - cmake
  - dataclasses
  - future
  - mkl
  - mkl-include
  - ninja
  - numpy
  - pytorch::magma-cuda118
  - pyyaml
  - requests
  - setuptools
  - six
  - typing_extensions
