channels:
  - conda-forge

dependencies:
  - beautifulsoup4
  - gensim
  - geopandas
  - matplotlib-base
  - mlflow
  - nltk
  - numpy
  - pandas
  - plotly
  - polars
  - seaborn
  - scikit-learn
  - scipy
  - spacy
  - statsmodels
  - xgboost
