name: Load Docker image
description: Download image tar and load it to docker

inputs:
  image:
    description: Image name
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Download built image ðŸ“¥
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.image }}
        path: /tmp/
    - name: Load downloaded image to docker ðŸ“¥
      run: |
        docker load < ${{ inputs.image }}.tar.gz
        docker image ls -a
      shell: bash
    - name: Delete the file ðŸ—‘ï¸
      run: rm -f /tmp/${{ inputs.image }}.tar.gz
      shell: bash
      if: always()