[tool.poetry]
name = "tools"
version = "0.1.0"
description = ""
authors = ["Alexis D <alexis.dondon@insee.fr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
