name: Download parent image, build new one, test it and upload to GitHub artifacts

on:
  workflow_call:
    inputs:
      parentImage:
        description: Parent image name
        required: true
        type: string
      image:
        description: Image name
        required: true
        type: string
      platform:
        description: Image platform
        required: true
        type: string
      runsOn:
        description: GitHub Actions Runner image
        required: true
        type: string

jobs:
  build-and-test:
    runs-on: ${{ inputs.runsOn }}
    steps:
      - name: Checkout Repo ⚡️
        uses: actions/checkout@v3
      - name: docker build
        run: docker build --build-arg BASE_IMAGE=ubuntu:20.04 ./base --tag jupyter/${{ inputs.image }} ${{ inputs.image }}/
      - name: run structure tests
        uses: plexsystems/container-structure-test-action@v0.1.0
        with:
          image: jupyter/${{ inputs.image }}
          config: ./base/tests.yaml
      #- name: Build image 🛠
      #  run: docker build --rm --force-rm --build-arg BASE_IMAGE=ubuntu:20.04 --tag jupyter/${{ inputs.image }} ${{ inputs.image }}/
      #  env:
      #    DOCKER_BUILDKIT: 1
      #    # Full logs for CI build
      #    BUILDKIT_PROGRESS: plain
      #  shell: bash
