name: Download parent image, build new one, test it and upload to GitHub artifacts

on:
  workflow_call:
    inputs:
      parentImage:
        description: Parent image name
        required: true
        type: string
      image:
        description: Image name
        required: true
        type: string
      platform:
        description: Image platform
        required: true
        type: string
      runsOn:
        description: GitHub Actions Runner image
        required: true
        type: string

jobs:
  build-test-upload:
    runs-on: ${{ inputs.runsOn }}
    steps:
      - name: Checkout Repo ⚡️
        uses: actions/checkout@v3
      - name: Create dev environment 📦
        uses: ./.github/actions/create-dev-env
        with:
          platform: ${{ inputs.platform }}
      - name: Build image 🛠
        run: docker build --rm --force-rm --build-arg BASE_IMAGE=ubuntu:20.04 --tag jupyter/${{ inputs.image }} ${{ inputs.image }}/
        env:
          DOCKER_BUILDKIT: 1
          # Full logs for CI build
          BUILDKIT_PROGRESS: plain
        shell: bash
