name: jupyter-r

on:
  workflow_dispatch:
  workflow_run:
    workflows: [r-datascience]
    types:
      - completed

jobs:
  base:
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: jupyter-r
      context: jupyter-r
      test: false
      push: true
      base_image: inseefrlab/onyxia-r-datascience:latest
      base_image_gpu: inseefrlab/onyxia-r-datascience:latest-gpu
