name: jupyter-pyspark

on:
  workflow_dispatch:
  workflow_run:
    workflows: [pyspark]
    types:
      - completed

jobs:
  base:
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: jupyter-pyspark
      context: jupyter
      test: false
      push: true
      base_image: inseefrlab/onyxia-pyspark:latest
      base_image_gpu: inseefrlab/onyxia-pyspark:latest-gpu
