name: python-datascience

on:
  workflow_dispatch:
  workflow_run:
    workflows: [python-minimal]
    types:
      - completed

jobs:
  base:
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: python-datascience
      context: python-datascience
      test: false
      push: true
      base_image: inseefrlab/onyxia-python-minimal:latest
      base_image_gpu: inseefrlab/onyxia-python-minimal:latest-gpu
