name: r-datascience

on:
  workflow_dispatch:
  workflow_run:
    workflows: [r-minimal]
    types:
      - completed

jobs:
  base:
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: r-datascience
      context: r-datascience
      test: false
      push: true
      base_image: inseefrlab/onyxia-r-minimal:latest
      base_image_gpu: inseefrlab/onyxia-r-minimal:latest-gpu
