name: r-minimal

on:
  workflow_dispatch:
  workflow_run:
    workflows: [base]
    types:
      - completed

jobs:
  base:
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: r-minimal
      context: r-minimal
      test: false
      push: true
      base_image: inseefrlab/onyxia-base:latest
      base_image_gpu: inseefrlab/onyxia-base:latest-gpu
